#!/bin/bash
source calc
source search
source reverse
source strlen
source log
source exit_
source help
source interactive
case $1 in
  calc) calc "${@:2}";;
  search) search "${@:2}";;
  reverse) reverse "${@:2}";;
  strlen) strlen "${@:2}";;
  log) log;;
  exit) exit_ "${@:2}";;
  help) help;;
  interactive) interactive;;
  *) echo "Invalid key!" >&2; return -1;;
esac

