#!/bin/bash
source calc
source search
source reverse
source strlen
source log
source exit_
source help
source interactive
case $1 in
  calc) calc "$2" "$3" "$4";;
  search) search "$2" "$3";;
  reverse) reverse "$2" "$3";;
  strlen) strlen "$2";;
  log) log;;
  exit) exit_ "$2";;
  help) help;;
  interactive) interactive;;
  *) echo "Invalid key!";;
esac

