#!/bin/bash

strlen () {
 if [[ $# -lt 1 ]]; then echo "Not enough arguments!" >&2; return -4; fi
 if [[ "$1" = "" ]]; then
   echo "Length of string: 0"
   return 0
 fi
 echo "Length of string: $(expr length "$1")"
}
